Global:
  use_gpu: true
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/anbofu_pretrain_1124/
  save_epoch_step: 1
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 5000]
  # 1. If pretrained_model is saved in static mode, such as classification pretrained model
  #    from static branch, load_static_weights must be set as True.
  # 2. If you want to finetune the pretrained models we provide in the docs,
  #    you should set load_static_weights as False.
  load_static_weights: True
  cal_metric_during_train: False
  pretrained_model: ./pretrained/ch_ppocr_server_v2.0_det_train
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: ResNet
    layers: 18
    disable_se: True
  Neck:
    name: DBFPN
    out_channels: 256
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /mnt/data/users/tairuqiu/workspace/datasets
    label_file_list:
      - /mnt/data/users/tairuqiu/workspace/datasets/anbofu_synth_data01/full_annotated/train/label.txt
      - /mnt/data/users/tairuqiu/workspace/datasets/anbofu_synth_data02/full_annotated/train/label.txt
    ratio_list: [1.0, 2.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Resize, 'args': { 'size': [0.5, 3] } }
            - { 'type': MultiplyBrightness, 'args': { 'mul': [0.25, 1.25] } }
            - { 'type': MultiplySaturation, 'args': { 'mul': [0.5, 1.5] } }
            - { 'type': Sometimes,
                'args': {
                  'p': 0.2,
                  'then_list': [{ 'type': GaussianBlur, 'args': { 'sigma': [0.1, 2.0] } }] } }
      - EastRandomCropData:
          size: [1152, 800]
          max_tries: 50
          min_crop_side_ratio: [0.1, 0.5]
          keep_ratio: true
          min_text_size: 5
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask'] # the order of the dataloader list
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 8
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /mnt/data/users/tairuqiu/workspace/datasets
    label_file_list:
      - /mnt/data/users/tairuqiu/workspace/datasets/anbofu_synth_data01/full_annotated/test/label.txt
      - /mnt/data/users/tairuqiu/workspace/datasets/anbofu_synth_data01/full_annotated/test/label.txt
    ratio_list: [1.0, 1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
#           image_shape: [736, 1280]
          limit_side_len: 3840
          limit_type: max
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 2
